### ISSUE TITLE
Progressive Fallback Ramp-Ups for Providers

### ISSUE THREAD

**Issue by Pratham-Mishra04** [maximhq/bifrost#120]
Introduce **progressive fallback ramp-up logic** when switching providers/models.

### Example Scenario:

1. **Primary provider fails.**
2. Instead of sending 100% of requests to fallback, we progressively ramp:

   * 10% → 25% → 50% → 100% over a configurable window.
3. If primary recovers, traffic is gradually moved back.

```yaml
fallback_ramp:
  strategy: progressive
  intervals:
    - percentage: 25
      after: 30s
    - percentage: 50
      after: 1m
```

### Why

* Avoids overloading fallback providers during large failover events.
* Ensures graceful degradation and stabilization during outages.
