### ISSUE TITLE
Progressive Ramping After Provider or API Key Failure

### ISSUE THREAD

**Issue by Pratham-Mishra04** [maximhq/bifrost#125]
When an **API key** for a provider gets rate-limited or invalidated, fallback should **ramp progressively** similar to provider fallbacks.

* Configurable ramp-up percentages.
* Auto-unblock when the key is recovered.

```yaml
api_key_ramp:
  on_failure:
    - percentage: 20
      after: 15s
```

### Why

Protects fallback keys/providers from sudden spikes and ensures predictable failover behavior.
