### ISSUE TITLE
Dynamic Scaling of Worker Pool and Buffer Sizes per Provider

### ISSUE THREAD

**Issue by Pratham-Mishra04** [maximhq/bifrost#128]
Currently in Bifrost, **each provider has a static configuration** for:

* **Buffer sizes** (pending request queues)
* **Worker pool sizes** (concurrent upstream request handlers)

This leads to two key problems:

1. ⚠️ **Bottleneck under load:** If a large number of requests target a provider with small worker/buffer limits, it becomes a **throttle point**.
2. ⚠️ **Wasted resources under-utilized:** If no traffic routes to a provider, its pre-allocated **memory and goroutines** sit idle.

### ✅ **Proposed Solution:**

Introduce **dynamic, runtime-adjustable scaling** of these resource allocations on a **per-provider** basis:

#### Features:

* **Auto-scaling** worker pool size based on real-time metrics:

  * Request arrival rate
  * Queue size thresholds
  * Latency feedback loops (optional)
* **Hot reloadable configuration:**

  * Allow updating **buffer size** and **worker count** *without restarting Bifrost*.
* **Optional static mode**:

  * Per-provider option to **opt out** of dynamic scaling for predictable environments.

#### Example Config (YAML):

```yaml
providers:
  - name: openai
    dynamic_worker_scaling: true
    min_workers: 4
    max_workers: 100
    scale_up_threshold: 70%  # when buffer usage exceeds 70%, add workers
    scale_down_threshold: 20% # shrink pool if buffer usage drops below 20%
```

#### Real-time Adjustments:

```
[INFO] openai workers scaled up to 64 (buffer utilization: 85%)
[INFO] openai workers scaled down to 16 (idle, low request rate)
```

### Why

* ⚡ **Prevents provider bottlenecks during traffic spikes.**
* ♻️ **Optimizes memory and goroutine usage** during idle periods.
* 🖥️ Supports **production-grade, zero-downtime configuration changes**.
